---
deployment:
  tasks:
    - export DEPLOYPATH=/home/eventli1/public_html/elm
    - cd $DEPLOYPATH
    - ~/bin/composer/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan db:seed --force
    - /usr/local/bin/php artisan optimize:clear
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan optimize
